### ISSUE TITLE
Contraints example hangs when run against Accumulo 3.x

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#110]
The Constraints example hangs when running 

`./bin/runex constraints.MaxMutationSize`

**Comment by Manno15** [comment]
An error does seem to occur but it is not the expected exception in the example. The log in the monitor is: `org.apache.accumulo.server.rpc.CustomNonBlockingServer$CustomFrameBuffer: Read a frame size of 30555947, which is bigger than the maximum allowable frame size 16384000 for ALL connections.` 

I will look into why this is the case for `MaxMutationSize` but not the others.

**Comment by Manno15** [comment]
Seems this specific error was discussed in https://github.com/apache/accumulo/issues/3042 and https://github.com/apache/accumulo/issues/3094. Unsure how those relate to this example, if at all, but it does seem to be a byproduct of trying to add such a large mutation.

**Comment by Manno15** [comment]
This example now works as expected with the changes from https://github.com/apache/accumulo/pull/3134. Once that is merged (and forwarded to the 3.0 branch), and you confirm @jmark99, this can be closed.

**Comment by jmark99** [comment]
Verified that example now works as expected. Closing #110.
