### ISSUE TITLE
README and HADOOP_VERSION variable minor issues

### ISSUE THREAD

**Issue by kevinrr888** [apache/accumulo-examples#123]
* User should ensure accumulo-env.sh (in their accumulo installation) is configured before moving on to step 4.
* HADOOP_VERSION variable should use HADOOP_HOME variable.

**Comment by EdColeman** [comment]
Thanks for reporting - do you intend to submit a PR with corrections?  If so, I can try and assign this issue to you,

**Comment by kevinrr888** [comment]
Yes, I just created the PR
