### ISSUE TITLE
Connector.builder().usingProperties("conf/accumulo-client.properties").build()

### ISSUE THREAD

**Issue by estkae** [apache/accumulo-examples#27]
if I create the package then this issue pop up:
ERROR] /home/hadoop/fluo-uno/accumulo-examples/src/main/java/org/apache/accumulo/examples/bloom/BloomFilters.java:[35,36] cannot find symbol
  symbol:   method builder()
  location: class org.apache.accumulo.core.client.Connector
This issue is on all java file how have the fix usingProperties. Connector.builder does occurs in Accumulo-connector.

**Comment by mikewalch** [comment]
Thanks for creating this issue.  This needs to be fixed. Accumulo examples depends on Accumulo 2.0.0-SNAPSHOT and the API has changed.  The Accumulo examples code just needs to be update to the latest API. I think it makes to base it off `2.0.0-alpha-1`.

**Comment by mikewalch** [comment]
I opened PR #28 which should fix this issue
