### ISSUE TITLE
Refactor out non API code

### ISSUE THREAD

**Issue by milleruntime** [apache/accumulo-examples#35]
With the import-control checkstyle, it is now easier to detect use of non-API code used.  The following exceptions should be refactored and removed from the config file:
https://github.com/apache/accumulo-examples/blob/master/contrib/import-control.xml#L36

**Comment by Manno15** [comment]
I was looking into this issue and after removing the exceptions and rebuilding/retesting I didn't notice any errors or changes. Can you elaborate on what you mean with this issue and if there is anything in addition that must be done or anything that I am missing? Thanks!

**Comment by milleruntime** [comment]
@Manno15 try buliding the project with "mvn clean install" or "mvn clean verify".

**Comment by milleruntime** [comment]
I just updated the build script to call verify and make sure it passes all the checks.  So if you pull down the update and run ./bin/build it should run checkstyle as well.

**Comment by Manno15** [comment]
Thanks, I will run it now and see what happens.

**Comment by Manno15** [comment]
Is the goal to change how the import control works so we don't need those exceptions or to change where they are used so we do not need the imports? Just a little confusion on wording. Thanks!

**Comment by milleruntime** [comment]
> to change where they are used so we do not need the imports? 

Yes.  Change the code that uses these imports so we can remove the exceptions from the import-control file.

**Comment by ctubbsii** [comment]
@Manno15 The intention here is to provide examples that a user could reasonably expect to write and use. However, we're currently doing things in these examples that are not recommended for users... like using internal-only unstable APIs. These aren't stable, and this practice makes for bad examples.

The intent of this ticket is to migrate those "bad" code examples away from using Accumulo internal classes (represented by the imported classes that we'd prefer to ban). This may mean getting rid of bad examples entirely... or it may mean rewriting them or simplifying them to avoid importing internal/unstable code from Accumulo's internals.

**Comment by Manno15** [comment]
Okay, that makes a lot of sense. Thank you both for clarifying for me.

**Comment by Manno15** [comment]
Considering that the Trace Dump is not under the listed examples, would that be one where we would get rid of entirely? Only thing the exception blocks is the actual printing of the trace.

**Comment by milleruntime** [comment]
> Considering that the Trace Dump is not under the listed examples, would that be one where we would get rid of entirely? Only thing the exception blocks is the actual printing of the trace.

We have plans to remove the Tracer (eventually) from Accumulo so perhaps leave that one for now.  I am not sure if the Tracer will be deleted or moved to its own repository.  @ctubbsii knows more about the Tracer so maybe he can weight in on what to do with this example.

**Comment by Manno15** [comment]
I am working on a different way to print it, similar to some of the other examples.

**Comment by ctubbsii** [comment]
I'm not familiar with the trace example, but it was my intention to deprecate and/or remove the tracer (sink) service, and investigate updating the trace instrumentation we're using. A good trace example would use custom trace sink specifically for that example rather than rely on the tracer service or its storage back into Accumulo.

**Comment by Manno15** [comment]
The one I was more talking about was the TraceDump example which seems to scan a table that then uses TraceDump to print Trace info and tserver info neatly. The tracing Example that is apart of the second exception on the list to remove still seems to work normally even with Distributed Trace removed. So I am not quite sure where to go for those two.

**Comment by ctubbsii** [comment]
TraceDump is part of the tracer sink service we provide (`trace.span.receivers = org.apache.accumulo.tracer.ZooTraceClient`) which receives spans and stores them back into an Accumulo table. TraceDump is not public API (no part of the tracer service is), but was presumably written as a utility to view and verify the data that has been received and stored by that tracer service.

The example should either be removed, or modified to set a different span receiver that is more suitable for an example. If it's difficult to remove, I would just move on to the others for now. There's no urgency to that.

**Comment by Manno15** [comment]
The example itself isn't directly tied to anything so it shouldn't be hard to remove. I can take a look at modifying it to set a different span receiver after I finish going through the rest if that is more preferable.

**Comment by ctubbsii** [comment]
@Manno15 Don't feel like this needs to all be fixed in a single pass. The use of internal, non-public APIs, in the examples can be fixed incrementally. :smiley_cat:

**Comment by Manno15** [comment]
I will keep that in mind. Thanks!
