### ISSUE TITLE
Add a delete key/value pair example

### ISSUE THREAD

**Issue by elinaawise** [apache/accumulo-examples#41]
While going through accumulo-examples, I wanted to understand what happens when a key/value pair has been deleted.  The steps in this example walk through seeing the delete flag, compaction, flush, and viewing the compacted file to ensure the deleted pair was removed.

**Comment by ctubbsii** [comment]
This is a great idea. Are you working on creating this example?

**Comment by elinaawise** [comment]
Yes, I will be checking it in shortly.

**Comment by elinaawise** [comment]
Is there a better way to find which Hadoop table name the RFile is in then looking in localhost:9995/tables?

**Comment by EdColeman** [comment]
The table name / id can be identified with TableOperations - either list() or tableIdMap(). 

You may want to also look at locate() - or the info would be in the metadata table - the column family file should point the files in hdfs before and then after the compaction.

Generally, (and if I recall correctly) once you have the table id, then scan the metadata table - a shell command is something like:

> scan -t accumulo.metadata -b [id]; -e [id]< -c file -np

**Comment by elinaawise** [comment]
@keith-turner This issue should be closed
