### ISSUE TITLE
Bulk Ingest example does not process correctly.

### ISSUE THREAD

**Issue by jzgithub1** [apache/accumulo-examples#55]
It does not find the split file so it does not create 3 map/reduce jobs.  It then does not properly ingest the data into the test table in Accumulo.

**Comment by EdColeman** [comment]
I thought it would create 1 M/R job, but use 3 reducers - depending on how the "cluster" is defined, there may only be 1 node for the reducers to run on, but the end result should be 3 files with the start / ends keys defined by the splits. Do you get 1 file, or more?

**Comment by jzgithub1** [comment]
Here is the result I see when I run BulkIngestExample inside of my Intellij debugger and not using the bin/runmr launcher that uses yarn (I get three reducers like you say because the split file is found in the cache - which is what I am testing really for my accumulo-1052 fix) :

 ls -R /tmp/bulkWork/
/tmp/bulkWork/:
failures  files  splits.txt

/tmp/bulkWork/failures:

/tmp/bulkWork/files:
part-r-00000.rf  _SUCCESS

**Comment by EdColeman** [comment]
What is in the splits file?  And what do you get if you run rfile-info on part-r-00000.rf file?  Basically, did all of your data end-up in one file because of the data? Say the splits were H,P, and T and you data all starts with Z.

**Comment by jzgithub1** [comment]
This worked when I updated my accumulo version.
