### ISSUE TITLE
The classpath example fails to load FooFilter.jar in 2.1.x

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#66]
When run against Accumulo-2.1.x, the classpath example fails to load the FooFilter.jar iterator. A ReflectiveOperationsException is thrown.

**Comment by milleruntime** [comment]
I am seeing this error when running the command:
`root@uno nofoo> setiter -n foofilter -p 10 -scan -minc -majc -class org.apache.accumulo.test.FooFilter`
<pre>
2021-03-25T15:55:23,854 [shell.Shell] ERROR: org.apache.accumulo.shell.ShellCommandException: Command could not be initialized (Unable to load org.apache.accumulo.test.FooFilter; class not found.)
</pre>

**Comment by milleruntime** [comment]
I wonder if this is realted to the changes here: https://github.com/apache/accumulo/pull/1715

**Comment by jmark99** [comment]
That is where I see the error as well. I haven't looked any further into this issue to date. But there have definitely been classloader modifications so perhaps.

**Comment by milleruntime** [comment]
This should be fixed with https://github.com/apache/accumulo/pull/1979
