### ISSUE TITLE
Shard portion of Sample example not producing expected results

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#76]
The Sample example uses results from the Shard example to illustrate some sampling behavior. The output of this section is not producing the expected results.

**Comment by DomGarguilo** [comment]
When this is addressed, it should also be added to the instructions that the Shard example needs to be run before the Shard portion of the Sample example. Or, include instructions on how to get to a point where the Shard portion of the Sample example can be run on its own.

**Comment by DomGarguilo** [comment]
Also, the table reference should be updated to include the namespace on this line:
https://github.com/apache/accumulo-examples/blob/99267730d55b11dadb59a6d3893ab95bcddd37f4/docs/sample.md?plain=1#L153

**Comment by jmark99** [comment]
@DomGarguilo the two previous comments have been addressed in #101 .

**Comment by jmark99** [comment]
With the https://github.com/apache/accumulo/pull/3193 update to Accumulo, the shard portion of the sample example now works correctly.
