### ISSUE TITLE
Update README.md to clarify use of 'main' vs '2.0' branch.

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#79]
The documentation does not make clear that the main branch is designed to work with the current development branch of Accumulo. If a user needs to run the examples against Accumulo 2.0.x, then the 2.0 branch should be used.

Update documentation to clarify this distinction.

Additionally, we could add a link to the 1.10.x examples if a user is looking for them (https://accumulo.apache.org/1.10/examples/).

**Comment by jmark99** [comment]
This issue was moved from the Accumulo repo to the Accumulo-Examples repo. See https://github.com/apache/accumulo/issues/2204 for previous version of ticket.

**Comment by ctubbsii** [comment]
@jmark99 Since I transferred apache/accumulo#2204 to this repo, there is no need for a second issue. I am closing this one, since #80 is sufficient and already has comments on it.
