### ISSUE TITLE
Update README.md to clarify use of 'main' vs '2.0' branch.

### ISSUE THREAD

**Issue by jmark99** [apache/accumulo-examples#80]
The documentation does not make clear that the main branch is designed to work with versions 2.1.x of Accumulo. If a user needs to run the examples against Accumulo 2.0.x, then the 2.0 branch should be used.

Update documentation to clarify this distinction. 

Additionally,  we could add a link to the 1.10.x examples if a user is looking for them (https://accumulo.apache.org/1.10/examples/).

**Comment by ctubbsii** [comment]
@jmark99 You can transfer issues between repos on GitHub, just like in JIRA. I transferred this issue.
