### ISSUE TITLE
Compaction Strategy Example is no longer accurate

### ISSUE THREAD

**Issue by Manno15** [apache/accumulo-examples#82]
The compaction strategy example should be updated to reflect the recent changes to compaction configuration in accumulo. Including the description of the strategies and the example configuration given. 
Example below of what could be added to replace the current example (this is found I'm accumulo-testing)
<pre>
tserver.compaction.major.service.cs1.planner=org.apache.accumulo.core.spi.compaction.DefaultCompactionPlanner \
tserver.compaction.major.service.cs1.planner.opts.executors=\
[{"name":"small","type":"internal","maxSize":"16M","numThreads":8},\
{"name":"medium","type":"internal","maxSize":"128M","numThreads":4},\
{"name":"large","type":"internal","numThreads":2
</pre>

The blog post on the accumulo website also gives further details on how to configure the new compactions. 
https://accumulo.apache.org/blog/2021/07/08/external-compactions.html

**Comment by jmark99** [comment]
Closing. Fixed with commit #117.
