### ISSUE TITLE
Remove or update tracing example

### ISSUE THREAD

**Issue by ctubbsii** [apache/accumulo-examples#88]
Upstream Accumulo replaced HTrace with opentelemetry. As such, the current HTrace-based example no longer makes sense as-is. It should either be changed to an example with opentelemetry, or it should be removed.

**Comment by DomGarguilo** [comment]
This tracing related TODO might be able to be removed once this issue is resolved:
https://github.com/apache/accumulo-examples/blob/6d0ab9f820748d2d0612d6359fce408c6edb4d87/spark/contrib/import-control.xml#L36-L39
